### Задание 1

In [4]:
import numpy as np

In [12]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [14]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

### Задание 2

In [17]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [25]:
a_centered_sp_1column = [a_centered[i][0] for i in range(len(a_centered))]
a_centered_sp_2column = [a_centered[i][1] for i in range(len(a_centered))]
a_centered_sp = np.dot(a_centered_sp_1column, a_centered_sp_2column)
N = 5
cov_2attr = a_centered_sp / (N-1)
cov_2attr

2.0

### Задание 4

In [27]:
cov_2attr = np.cov(a.T)[0][1]
cov_2attr

2.0